### ISSUE TITLE
Reviews not loading in Safari

### ISSUE THREAD

**Issue by kmackinnon** [martzcodes/OMSCentral#10]
just seeing the placeholder image

**Comment by martzcodes** [comment]
@kmackinnon I'm not able to reproduce this... what version of safari are you on?  (For example I'm on 11.0.1).

**Comment by kmackinnon** [comment]
@martzcodes Now at home I'm unable to reproduce this as well, even though it happened consistently while I was using Safari on the corporate proxy at work. I'll close the issue for now and check again Monday - it's probably something on my end.

**Comment by martzcodes** [comment]
@kmackinnon maybe your work proxy doesn't play well with firebase?  Or I happened to fix it when I did a code post yesterday around 5PM ET (if you waited a few hours to report it, that could be the case)
