### ISSUE TITLE
Edit/delete buttons don't work in Chrome

### ISSUE THREAD

**Issue by Arkaaito** [martzcodes/OMSCentral#11]
On the profile and on course pages, e.g., https://omscentral.com/reviews/6300.

They don't throw any JS errors, they just don't... _do_ anything or make any network requests.

The one on the course page works OK in Safari, so this appears to be a browser-specific issue.  The one on the profile page throws an error in Safari:

TypeError: undefined is not an object (evaluating 'this.cached[t].reviews')

However, I didn't test here until _after_ I played around with deletion in both browsers, so this may be tied to that specific scenario.

**Comment by martzcodes** [comment]
@Arkaaito please close if fixed

**Comment by Arkaaito** [comment]
Verified!  That was fast.
