### ISSUE TITLE
adding date of when particular review was submitted

### ISSUE THREAD

**Issue by ayanovsk** [martzcodes/OMSCentral#13]
If possible, please, add the date of when particular review was submitted. It is convenient, in order to know that you have already seen some old reviews when you visited it last time, so you know on which new ones to focus.

**Comment by martzcodes** [comment]
@ayanovsk yeah... there are a handful (~20) reviews that didn't store a date for when they were created / updated.  Not much I can do about those... but I can tell you they were made between December 1st and December 5th

**Comment by ayanovsk** [comment]
Thanks, Matt; so those are very new Dec 1-Dec 5, 2017? Maybe then makes sense just to add Dec 3rd to them, so that folks do not have questions, when they do not see the date.

I am also wondering, if you want to add the author; I know majority of reviews are anonymous, but if it still allows to post not anonymous review, then probably it makes sense to show the author?

**Comment by martzcodes** [comment]
yeah I'll probably do that.

As far as anonymous, the reason I have that hidden at the moment is to reduce bandwidth (I don't have to download all the names if I don't show any of them).

**Comment by ayanovsk** [comment]
Indeed, names are probably not that important, anyway, almost all of them are anonymous,
 just maybe to explain somewhere to users, so they should not have questions, like I had.

**Comment by ayanovsk** [comment]
I'm actually pretty sure that some of those currently without dates are much earlier than Dec 1, 2017.

**Comment by martzcodes** [comment]
Hm, I was displaying the updated date, I guess if they were never modified then it doesn't store both.

**Comment by martzcodes** [comment]
cca9e8312e3512958e47f635f86e62fe336409d8
