### ISSUE TITLE
tables not sorting

### ISSUE THREAD

**Issue by kbohinski** [martzcodes/OMSCentral#14]

**Comment by martzcodes** [comment]
@kbohinski please provide more details.... which tables?

I just checked the review and grade summary tables and they sort/filter fine in both IE and Chrome

**Comment by kbohinski** [comment]
Hmm, I was trying to sort by withdrew on the grades page to get a feel of how hard a class was and it was not sorting on firefox.

**Comment by martzcodes** [comment]
Hmm... yeah looks like it doesn't like the blanks (when I clicked through I only clicked a few columns)

valid bug, thanks
