### ISSUE TITLE
CSE 6250 and CS 6250 have same values for some of the fields

### ISSUE THREAD

**Issue by AliMur** [martzcodes/OMSCentral#49]
It looks like the code isn't considering the course's department when pulling stats for a course, because of this CSE 6250 and CS 6250 show same stats. See screenshot.

![omscentral_bug](https://user-images.githubusercontent.com/10201789/36923300-72a0e056-1e30-11e8-9f10-22783c566bbd.PNG)

**Comment by martzcodes** [comment]
Thanks Ali... that's going to be a fun one to fix...

**Comment by martzcodes** [comment]
Oh, it's just the grades... that won't be too bad I think

**Comment by martzcodes** [comment]
Related to #46
