### ISSUE TITLE
Can't Access Course Reviews

### ISSUE THREAD

**Issue by TommyJohnDub** [martzcodes/OMSCentral#50]
When I access [https://omscentral.com/courses](https://omscentral.com/courses), all the course reviews are empty. Am I doing something wrong? 

![screen shot 2018-03-19 at 11 53 32 am](https://user-images.githubusercontent.com/1634329/37616137-3a763340-2b6c-11e8-9518-0b0c407c2843.png)

**Comment by martzcodes** [comment]
@TommyJohnDub 

Try refreshing the page?

What type of account did you use to log in with (i.e. username/password, facebook, github, etc)?

Are there any errors in the developer console?

Can you try chrome?

I just checked on my work computer (PC w/Chrome) and it loaded fine.

It looks like you're logged in but you only have About/Courses/Donate in your menu which is odd.

**Comment by TommyJohnDub** [comment]
Thanks @martzcodes 

For whatever reason it logs me in automatically to an account that is not mine. After logging out of that account and logging in with my Google account:
1.) On Safari, I can only see recent course reviews
2.) On Chrome everything works

I had been using Safari before without any issues but I will use Chrome moving forward. Thanks for the prompt response.
