### ISSUE TITLE
Empty course showing info

### ISSUE THREAD

**Issue by hdchan** [martzcodes/OMSCentral#67]
Actual: When navigating to a course with no recorded information, info from a previously navigated course will appear

Expected: There should be no info on detail page when there is no recorded reviews

Steps to reproduce:
1. Navigate to any course detail page (excluding CSE-6140)
2. Navigate to CSE-6140

![screen shot 2018-07-02 at 5 23 25 pm](https://user-images.githubusercontent.com/4207605/42187020-a534ba3c-7e1c-11e8-9b63-dc58802f2cf0.png)

![screen shot 2018-07-02 at 5 22 56 pm](https://user-images.githubusercontent.com/4207605/42186995-9501d492-7e1c-11e8-8a4b-6f3ac156b74e.png)

**Comment by martzcodes** [comment]
Thanks, I'll take a look
