### ISSUE TITLE
courses with 0 reviews display reviews from other courses

### ISSUE THREAD

**Issue by redscare373** [martzcodes/OMSCentral#73]
Filtering performed before reading reviews: typed"ISYE" in the filter, sorted the courses by number of reviews in ascending order (0, 1, etc reviews), out of curiosity clicked on a course with 0 reviews and the resulting review was from a first course below that had 1 review ("ISYE-6644 Simulation"). Same happened with descending order, except now the 1-review simulation course was above the 0-review courses.

**Comment by martzcodes** [comment]
Should be related to #67 which was fixed.

@redscare373 can you clear your cache and try again?  I suspect this is because I didn't update the serviceworker and the page code is being aggressively cached

**Comment by redscare373** [comment]
You're right, that did the trick! I did look through prior issues, didn't realize these are related. Thank you!
