### ISSUE TITLE
Give each review it's own URL that can be shared 

### ISSUE THREAD

**Issue by gcoladon** [martzcodes/OMSCentral#79]
Sometimes while I'm reading reviews, I'll find one that I want to share with a classmate. Sadly, I can't figure out how to do it, other than by copying and pasting the text of the review into an email.

Ideally, the timestamp at the top right, e.g. "7/19/18, 6:48 PM", would be clickable and take the user to a URL for that specific review, which could then be shared easily with someone else.

**Comment by martzcodes** [comment]
@gcoladon it's deployed.  Might need to clear your cache though

**Comment by gcoladon** [comment]
I opened the site in an incognito window and that did the trick. Your anchor method works great! Issue complete.
