### ISSUE TITLE
Fall 2018 review option not available

### ISSUE THREAD

**Issue by reviewer6** [martzcodes/OMSCentral#82]
Fall 2018 review options not available . Also list down does not show 'AI for Robotics' option while writing a review.

**Comment by martzcodes** [comment]
Clear your cache

**Comment by martzcodes** [comment]
Also AI4R is there, listed as CS-8803-O01 . ... the list does appear to be unsorted.  I should add that and add in typeahead...

**Comment by reviewer6** [comment]
Thanks, yes AI for Robotics reviews are available. Somehow I still see Summer 2018 as the last one in 'semester*' dropdown

**Comment by martzcodes** [comment]
Other people have reported this... I'm not sure how to fix it at this point because it works on some peoples and not others... very hard to troubleshoot.

Try using a different browser?

**Comment by reviewer6** [comment]
yes, strange . in IE I am able to see Fall, 2018 but not in Chrome.

**Comment by achintkv** [comment]
I've got the same issue in Chrome, works in Firefox though.
