### ISSUE TITLE
average ratings fall outside the range 0-5

### ISSUE THREAD

**Issue by mhouston-git** [martzcodes/OMSCentral#9]
Three courses currently have average ratings outside the range 0-5

CS6262 Average Rating = -6,905,967,866,320,286,000
CS6300 Average Rating = 37.221
CS6750 Average Rating = 43.421

This looks a bug where invalid data is being included in the average.

If it matters, I see this on Firefox Quantum (57.0) running on Linux Mint.

**Comment by mhouston-git** [comment]
I suspect that changing these lines 
```
if (review.rating) {
  rating += review.rating;
  ratingNum++;
}
```

In count-update.js to 
```
if (review.rating && (review.rating<=5) && (review.rating>=0)) {
  rating += review.rating;
  ratingNum++;
}
```

would fix the problem. It might be better to find the offending database entries and purge them though.

**Comment by martzcodes** [comment]
@mhouston-git when I run it locally with the backed-up database the values I get are reasonable and I don't see any ratings, etc higher than 5.  In functions/index.js (where the google cloud functions live) I suspect it has something to do with the promises.  But I won't get to this until next week at the earliest.

I did do a code post yesterday, and when viewing a course review page (i.e. /reviews/6250) it calculates the totals in the browser and then caches them (pretty sure I added the caching) for use on the summary page (/reviews).  So at least if someone logs in and tries to figure out why something has a rating of 25 it should resolve itself

**Comment by martzcodes** [comment]
@mhouston-git although, looking at https://omscentral.com/reviews/6262 apparently that's not working either

**Comment by martzcodes** [comment]
@mhouston-git turns out it was a problem between strings and ints.  Fixed it on the front end, updated the cloud functions but they won't recalculate until a review is updated (I'll have to force that later).  I'll leave this open til I manually force the update

**Comment by Arkaaito** [comment]
Fixed for SDP, looks like someone else already fixed it for NetSec and HCI.

**Comment by ayanovsk** [comment]
If possible, please, add the date of when particular review was submitted. It is convenient, in order to know that you have already seen some old reviews when you visited it last time,  so you know on which new ones to focus.
